# AWS CodeBuild Specification file
# This file specify instructions to build the image and
# push it to Amazon ECR repository
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Done! Successfully logged in to Amazon ECR.
  build:
    commands:
      - export BRANCH_NAME=$(git branch --show-current)
      - export GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
      - export APP_VERSION=$(grep -o '\"version\": \"[^\"]*' version.json | grep -o '[^"]*$')
      - export IMAGE_TAG=$APP_VERSION-$GIT_COMMIT_HASH
      - echo Working on branch=\'$BRANCH_NAME\'\, git commit hash=\'$GIT_COMMIT_HASH\'\, and app version=\'$IMAGE_TAG\'
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile -t thislocal/microapp .
      - echo Done! Build completed on `date`.
#      - echo Running unit tests...
#      - docker run -it thislocal/microapp python test.py
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Pushing the Docker image to \'$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME\' ...
      - docker tag thislocal/microapp $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag thislocal/microapp $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Done! Docker image successfully pushed to repository.
      - echo Completed! Build process completed on `date`.
